# Generated by Django 5.0 on 2025-11-30 03:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapApp', '0004_alter_mensaje_contenido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='visitas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='SwapApp.categoria'),
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrellas_totales', models.PositiveIntegerField(default=0)),
                ('cantidad_calificaciones', models.PositiveIntegerField(default=0)),
                ('suspendido', models.BooleanField(default=False)),
                ('razon_suspension', models.CharField(blank=True, max_length=300)),
                ('fecha_suspension', models.DateTimeField(blank=True, null=True)),
                ('advertencias', models.PositiveIntegerField(default=0)),
                ('intereses', models.CharField(blank=True, help_text='Intereses separados por comas. Ej: tecnología,ropa,hogar', max_length=300)),
                ('favoritos', models.ManyToManyField(blank=True, related_name='favoritos_de', to='SwapApp.producto')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='producto',
            name='tags',
            field=models.ManyToManyField(blank=True, to='SwapApp.tag'),
        ),
    ]
