# Generated by Django 5.0 on 2025-11-30 19:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SwapApp', '0006_calificacion_moderacion_reporte'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='estrellas',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterUniqueTogether(
            name='calificacion',
            unique_together={('vendedor', 'comprador', 'trueque')},
        ),
    ]
